//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculationTask
    {
        public long id { get; set; }
        public short task_type { get; set; }
        public string description { get; set; }
        public Nullable<short> status { get; set; }
        public int user_id { get; set; }
        public System.DateTimeOffset created { get; set; }
        public Nullable<System.DateTimeOffset> started { get; set; }
        public Nullable<System.DateTimeOffset> completed { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
