//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculationTask
    {
        public long Id { get; set; }
        public LibiadaWeb.Tasks.TaskType TaskType { get; set; }
        public string Description { get; set; }
        public LibiadaWeb.Tasks.TaskState Status { get; set; }
        public string Result { get; set; }
        public string AdditionalResultData { get; set; }
        public int UserId { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public Nullable<System.DateTimeOffset> Started { get; set; }
        public Nullable<System.DateTimeOffset> Completed { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
