//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculationTask
    {
        public long Id { get; set; }
        public LibiadaWeb.Tasks.TaskType TaskType { get; set; }
        public string Description { get; set; }
        public LibiadaWeb.Tasks.TaskState Status { get; set; }
        public string Result { get; set; }
        public string AdditionalResultData { get; set; }
        public int UserId { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public Nullable<System.DateTimeOffset> Started { get; set; }
        public Nullable<System.DateTimeOffset> Completed { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
