//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacteristicType
    {
        public CharacteristicType()
        {
            CharacteristicTypeLink = new HashSet<CharacteristicTypeLink>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> CharacteristicGroupId { get; set; }
        public string ClassName { get; set; }
        public bool FullSequenceApplicable { get; set; }
        public bool AccordanceApplicable { get; set; }
        public bool CongenericSequenceApplicable { get; set; }
        public bool BinarySequenceApplicable { get; set; }
    
        public virtual ICollection<CharacteristicTypeLink> CharacteristicTypeLink { get; set; }
        public virtual CharacteristicGroup CharacteristicGroup { get; set; }
    }
}
