//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class characteristic
    {
        public long id { get; set; }
        public long chain_id { get; set; }
        public int characteristic_type_id { get; set; }
        public Nullable<double> value { get; set; }
        public string value_string { get; set; }
        public Nullable<int> link_id { get; set; }
        public System.DateTimeOffset created { get; set; }
        public Nullable<System.DateTimeOffset> modified { get; set; }
    
        public virtual link link { get; set; }
        public virtual chain chain { get; set; }
        public virtual characteristic_type characteristic_type { get; set; }
    }
}
