//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongenericCharacteristicValue
    {
        public long Id { get; set; }
        public long SequenceId { get; set; }
        public short CharacteristicLinkId { get; set; }
        public double Value { get; set; }
        public long ElementId { get; set; }
    
        public virtual CongenericCharacteristicLink CongenericCharacteristicLink { get; set; }
        public virtual Element Element { get; set; }
    }
}
