//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongenericCharacteristicLink
    {
        public short Id { get; set; }
        public LibiadaCore.Core.Characteristics.Calculators.CongenericCalculators.CongenericCharacteristic CongenericCharacteristic { get; set; }
        public LibiadaCore.Core.Link Link { get; set; }
        public LibiadaCore.Core.ArrangementManagers.ArrangementType ArrangementType { get; set; }
    }
}
