//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element
    {
        public Element()
        {
            this.FirstElementBinaryCharacteristic = new HashSet<BinaryCharacteristic>();
            this.SecondElementBinaryCharacteristic = new HashSet<BinaryCharacteristic>();
            this.CongenericCharacteristic = new HashSet<CongenericCharacteristic>();
        }
    
        public long Id { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public int NotationId { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public System.DateTimeOffset Modified { get; set; }
    
        public virtual ICollection<BinaryCharacteristic> FirstElementBinaryCharacteristic { get; set; }
        public virtual ICollection<BinaryCharacteristic> SecondElementBinaryCharacteristic { get; set; }
        public virtual Notation Notation { get; set; }
        public virtual ICollection<CongenericCharacteristic> CongenericCharacteristic { get; set; }
    }
}
