//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element
    {
        public Element()
        {
            FirstElementBinaryCharacteristic = new HashSet<BinaryCharacteristic>();
            SecondElementBinaryCharacteristic = new HashSet<BinaryCharacteristic>();
            FirstElementAccordanceCharacteristic = new HashSet<AccordanceCharacteristic>();
            SecondElementAccordanceCharacteristic = new HashSet<AccordanceCharacteristic>();
            CongenericCharacteristic = new HashSet<CongenericCharacteristic>();
        }
    
        public long Id { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public Notation Notation { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public System.DateTimeOffset Modified { get; set; }
    
        public virtual ICollection<BinaryCharacteristic> FirstElementBinaryCharacteristic { get; set; }
        public virtual ICollection<BinaryCharacteristic> SecondElementBinaryCharacteristic { get; set; }
        public virtual ICollection<AccordanceCharacteristic> FirstElementAccordanceCharacteristic { get; set; }
        public virtual ICollection<AccordanceCharacteristic> SecondElementAccordanceCharacteristic { get; set; }
        public virtual ICollection<CongenericCharacteristic> CongenericCharacteristic { get; set; }
    }
}
