//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element
    {
        public Element()
        {
            this.FirstElementBinaryCharacteristic = new HashSet<BinaryCharacteristic>();
            this.SecondElementBinaryCharacteristic = new HashSet<BinaryCharacteristic>();
            this.FirstElementAccordanceCharacteristic = new HashSet<AccordanceCharacteristic>();
            this.SecondElementAccordanceCharacteristic = new HashSet<AccordanceCharacteristic>();
            this.CongenericCharacteristic = new HashSet<CongenericCharacteristic>();
        }
    
        public long Id { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public int NotationId { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public System.DateTimeOffset Modified { get; set; }
    
        public virtual ICollection<BinaryCharacteristic> FirstElementBinaryCharacteristic { get; set; }
        public virtual ICollection<BinaryCharacteristic> SecondElementBinaryCharacteristic { get; set; }
        public virtual ICollection<AccordanceCharacteristic> FirstElementAccordanceCharacteristic { get; set; }
        public virtual ICollection<AccordanceCharacteristic> SecondElementAccordanceCharacteristic { get; set; }
        public virtual Notation Notation { get; set; }
        public virtual ICollection<CongenericCharacteristic> CongenericCharacteristic { get; set; }
    }
}
