//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullCharacteristicLink
    {
        public short Id { get; set; }
        public LibiadaCore.Core.Characteristics.Calculators.FullCalculators.FullCharacteristic FullCharacteristic { get; set; }
        public LibiadaCore.Core.Link Link { get; set; }
    }
}
