//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class gene
    {
        public gene()
        {
            this.piece = new HashSet<piece>();
        }
    
        public long id { get; set; }
        public Nullable<System.DateTimeOffset> created { get; set; }
        public Nullable<System.DateTimeOffset> modified { get; set; }
        public long chain_id { get; set; }
        public int piece_type_id { get; set; }
        public string description { get; set; }
        public Nullable<int> web_api_id { get; set; }
        public bool complement { get; set; }
        public bool partial { get; set; }
        public Nullable<int> product_id { get; set; }
    
        public virtual dna_chain dna_chain { get; set; }
        public virtual piece_type piece_type { get; set; }
        public virtual product product { get; set; }
        public virtual ICollection<piece> piece { get; set; }
    }
}
