//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageSequence
    {
        public long Id { get; set; }
        public short Notation { get; set; }
        public LibiadaWeb.ImageOrderExtractor OrderExtractor { get; set; }
        public long MatterId { get; set; }
        public string RemoteId { get; set; }
        public Nullable<short> RemoteDb { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public System.DateTimeOffset Modified { get; set; }
    
        public virtual Matter Matter { get; set; }
    }
}
