//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class link
    {
        public link()
        {
            this.binary_characteristic = new HashSet<binary_characteristic>();
            this.characteristic = new HashSet<characteristic>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<binary_characteristic> binary_characteristic { get; set; }
        public virtual ICollection<characteristic> characteristic { get; set; }
    }
}
