//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class matter
    {
        public long id { get; set; }
        public string name { get; set; }
        public int nature_id { get; set; }
        public string description { get; set; }
        public System.DateTimeOffset created { get; set; }
        public Nullable<System.DateTimeOffset> modified { get; set; }
    
        public virtual nature nature { get; set; }
    }
}
