//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measure
    {
        public Measure()
        {
            this.BinaryCharacteristic = new HashSet<BinaryCharacteristic>();
            this.CongenericCharacteristic = new HashSet<CongenericCharacteristic>();
            this.Characteristic = new HashSet<Characteristic>();
        }
    
        public long Id { get; set; }
        public int NotationId { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public long MatterId { get; set; }
        public int PieceTypeId { get; set; }
        public long PiecePosition { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public int Beats { get; set; }
        public int Beatbase { get; set; }
        public Nullable<int> TicksPerBeat { get; set; }
        public int Fifths { get; set; }
        public Nullable<int> RemoteDbId { get; set; }
        public string RemoteId { get; set; }
        public System.DateTimeOffset Modified { get; set; }
    
        public virtual Matter Matter { get; set; }
        public virtual Notation Notation { get; set; }
        public virtual PieceType PieceType { get; set; }
        public virtual ICollection<BinaryCharacteristic> BinaryCharacteristic { get; set; }
        public virtual ICollection<CongenericCharacteristic> CongenericCharacteristic { get; set; }
        public virtual ICollection<Characteristic> Characteristic { get; set; }
        public virtual RemoteDb RemoteDb { get; set; }
    }
}
