//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measure
    {
        public Measure()
        {
            this.BinaryCharacteristic = new HashSet<BinaryCharacteristic>();
            this.CongenericCharacteristic = new HashSet<CongenericCharacteristic>();
            this.Characteristic = new HashSet<Characteristic>();
        }
    
        public long Id { get; set; }
        public int NotationId { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public long MatterId { get; set; }
        public int FeatureId { get; set; }
        public long PiecePosition { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public int Beats { get; set; }
        public int Beatbase { get; set; }
        public Nullable<int> TicksPerBeat { get; set; }
        public int Fifths { get; set; }
        public Nullable<int> RemoteDbId { get; set; }
        public string RemoteId { get; set; }
        public System.DateTimeOffset Modified { get; set; }
    
        public virtual Matter Matter { get; set; }
        public virtual Notation Notation { get; set; }
        public virtual Feature Feature { get; set; }
        public virtual ICollection<BinaryCharacteristic> BinaryCharacteristic { get; set; }
        public virtual ICollection<CongenericCharacteristic> CongenericCharacteristic { get; set; }
        public virtual ICollection<Characteristic> Characteristic { get; set; }
        public virtual RemoteDb RemoteDb { get; set; }
    }
}
