//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multisequence
    {
        public Multisequence()
        {
            Matters = new HashSet<Matter>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nature Nature { get; set; }
    
        public virtual ICollection<Matter> Matters { get; set; }
    }
}
