//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nature
    {
        public Nature()
        {
            this.Matter = new HashSet<Matter>();
            this.Notation = new HashSet<Notation>();
            this.Feature = new HashSet<Feature>();
            this.RemoteDb = new HashSet<RemoteDb>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Matter> Matter { get; set; }
        public virtual ICollection<Notation> Notation { get; set; }
        public virtual ICollection<Feature> Feature { get; set; }
        public virtual ICollection<RemoteDb> RemoteDb { get; set; }
    }
}
