//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class nature
    {
        public nature()
        {
            this.matter = new HashSet<matter>();
            this.notation = new HashSet<notation>();
            this.piece_type = new HashSet<piece_type>();
            this.remote_db = new HashSet<remote_db>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<matter> matter { get; set; }
        public virtual ICollection<notation> notation { get; set; }
        public virtual ICollection<piece_type> piece_type { get; set; }
        public virtual ICollection<remote_db> remote_db { get; set; }
    }
}
