//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nature
    {
        public Nature()
        {
            Matter = new HashSet<Matter>();
            Notation = new HashSet<Notation>();
            Feature = new HashSet<Feature>();
            RemoteDb = new HashSet<RemoteDb>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Matter> Matter { get; set; }
        public virtual ICollection<Notation> Notation { get; set; }
        public virtual ICollection<Feature> Feature { get; set; }
        public virtual ICollection<RemoteDb> RemoteDb { get; set; }
    }
}
