//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notation
    {
        public Notation()
        {
            this.Sequence = new HashSet<CommonSequence>();
            this.DnaSequence = new HashSet<DnaSequence>();
            this.Element = new HashSet<Element>();
            this.LiteratureSequence = new HashSet<LiteratureSequence>();
            this.Fmotiv = new HashSet<Fmotiv>();
            this.Measure = new HashSet<Measure>();
            this.MusicSequence = new HashSet<MusicSequence>();
            this.DataSequence = new HashSet<DataSequence>();
            this.Note = new HashSet<Note>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int NatureId { get; set; }
    
        public virtual ICollection<CommonSequence> Sequence { get; set; }
        public virtual ICollection<DnaSequence> DnaSequence { get; set; }
        public virtual ICollection<Element> Element { get; set; }
        public virtual ICollection<LiteratureSequence> LiteratureSequence { get; set; }
        public virtual Nature Nature { get; set; }
        public virtual ICollection<Fmotiv> Fmotiv { get; set; }
        public virtual ICollection<Measure> Measure { get; set; }
        public virtual ICollection<MusicSequence> MusicSequence { get; set; }
        public virtual ICollection<DataSequence> DataSequence { get; set; }
        public virtual ICollection<Note> Note { get; set; }
    }
}
