//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public Note()
        {
            Pitch = new HashSet<Pitch>();
        }
    
        public long Id { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public Notation Notation { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public int Numerator { get; set; }
        public int Denominator { get; set; }
        public int Onumerator { get; set; }
        public int Odenominator { get; set; }
        public bool Triplet { get; set; }
        public Nullable<int> Priority { get; set; }
        public LibiadaMusic.ScoreModel.Tie Tie { get; set; }
        public System.DateTimeOffset Modified { get; set; }
    
        public virtual ICollection<Pitch> Pitch { get; set; }
    }
}
