//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class piece_type
    {
        public piece_type()
        {
            this.chain = new HashSet<chain>();
            this.dna_chain = new HashSet<dna_chain>();
            this.literature_chain = new HashSet<literature_chain>();
            this.fmotiv = new HashSet<fmotiv>();
            this.measure = new HashSet<measure>();
            this.music_chain = new HashSet<music_chain>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int nature_id { get; set; }
    
        public virtual ICollection<chain> chain { get; set; }
        public virtual ICollection<dna_chain> dna_chain { get; set; }
        public virtual ICollection<literature_chain> literature_chain { get; set; }
        public virtual nature nature { get; set; }
        public virtual ICollection<fmotiv> fmotiv { get; set; }
        public virtual ICollection<measure> measure { get; set; }
        public virtual ICollection<music_chain> music_chain { get; set; }
    }
}
