//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class piece
    {
        public long id { get; set; }
        public long gene_id { get; set; }
        public int start { get; set; }
        public int length { get; set; }
    
        public virtual gene gene { get; set; }
    }
}
