//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class pitch
    {
        public int id { get; set; }
        public int octave { get; set; }
        public int midinumber { get; set; }
        public int instrument_id { get; set; }
        public long note_id { get; set; }
        public int accidental_id { get; set; }
        public int note_symbol_id { get; set; }
        public System.DateTimeOffset created { get; set; }
        public Nullable<System.DateTimeOffset> modified { get; set; }
    
        public virtual note note { get; set; }
        public virtual instrument instrument { get; set; }
        public virtual accidental accidental { get; set; }
        public virtual note_symbol note_symbol { get; set; }
    }
}
