//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pitch
    {
        public Pitch()
        {
            Note = new HashSet<Note>();
        }
    
        public int Id { get; set; }
        public int Octave { get; set; }
        public int Midinumber { get; set; }
        public Nullable<int> InstrumentId { get; set; }
        public Accidental Accidental { get; set; }
        public int NoteSymbolId { get; set; }
    
        public virtual Instrument Instrument { get; set; }
        public virtual NoteSymbol NoteSymbol { get; set; }
        public virtual ICollection<Note> Note { get; set; }
    }
}
