//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public long Id { get; set; }
        public long SubsequenceId { get; set; }
        public int Start { get; set; }
        public int Length { get; set; }
    
        public virtual Subsequence Subsequence { get; set; }
    }
}
