//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.dna_chain = new HashSet<dna_chain>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int piece_type_id { get; set; }
    
        public virtual ICollection<dna_chain> dna_chain { get; set; }
        public virtual piece_type piece_type { get; set; }
    }
}
