//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SequenceGroup
    {
        public SequenceGroup()
        {
            Matters = new HashSet<Matter>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public int CreatorId { get; set; }
        public System.DateTimeOffset Modified { get; set; }
        public int ModifierId { get; set; }
    
        public virtual ICollection<Matter> Matters { get; set; }
        public virtual AspNetUser Creator { get; set; }
        public virtual AspNetUser Modifier { get; set; }
    }
}
