//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibiadaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskResult
    {
        public long Id { get; set; }
        public long TaskId { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    
        public virtual CalculationTask Task { get; set; }
    }
}
